# Generated by Django 5.0.6 on 2024-06-29 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('closed', 'Clos')], default='pending', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Procès-verbal')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/', verbose_name='Fichier de preuve')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
