# Generated by Django 5.0.6 on 2024-07-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_identity', models.CharField(blank=True, default='Inconnu', max_length=100, null=True, verbose_name="Identité de l'agent")),
                ('complainant_name', models.CharField(default='Anonyme', max_length=100, verbose_name='Nom du plaignant')),
                ('complainant_address', models.TextField(default='Adresse non fournie', verbose_name='Adresse du plaignant')),
                ('complainant_email', models.EmailField(default='email@exemple.com', max_length=254, verbose_name='Email du plaignant')),
                ('complainant_phone', models.CharField(default='0000000000', max_length=15, verbose_name='Téléphone du plaignant')),
                ('complainant_sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe du plaignant')),
                ('subject', models.CharField(default='Sujet non défini', max_length=200, verbose_name='Sujet')),
                ('description', models.TextField(default='Pas de description fournie', verbose_name='Description/Detail')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('closed', 'Clos')], default='pending', max_length=20, verbose_name='Statut')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/', verbose_name='Fichier de preuve')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone')], default='email', max_length=10, verbose_name='Moyen de contact')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('complaint_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recommendations/', verbose_name='Fichier de recommandation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='clients.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Fichier de procès-verbal')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléchargement')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients.complaint')),
            ],
        ),
    ]
