# Generated by Django 5.0.6 on 2024-07-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date_created',
        ),
    ]
