# Generated by Django 5.0.6 on 2024-06-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='client',
        ),
    ]
