# Generated by Django 5.0.6 on 2024-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_complaint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='name',
            field=models.CharField(default='unknow user', max_length=20),
        ),
    ]
