# Generated by Django 5.0.6 on 2024-06-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_complaint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='agent_identity',
            field=models.CharField(blank=True, default='Inconnu', max_length=100, null=True, verbose_name="Identité de l'agent"),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_address',
            field=models.TextField(default='Adresse non fournie', verbose_name='Adresse du plaignant'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_email',
            field=models.EmailField(default='email@exemple.com', max_length=254, verbose_name='Email du plaignant'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(default='Anonyme', max_length=100, verbose_name='Nom du plaignant'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_phone',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Téléphone du plaignant'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complainant_sex',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Sexe du plaignant'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone')], default='email', max_length=10, verbose_name='Moyen de contact'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(default='Pas de description fournie', verbose_name='Description/Detail'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('closed', 'Clos')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(default='Sujet non défini', max_length=200, verbose_name='Sujet'),
        ),
    ]
