# Generated by Django 5.0.6 on 2024-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_utilisateur_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mail_user',
            field=models.CharField(default='mail@gmail.com', max_length=255),
        ),
    ]
